baseURL = "https://jianliew.me/blog"
languageCode = "en-us"
title = "Jian Liew"
theme = "hugo-theme-learn"
publishDir = "docs"
googleAnalytics = "UA-55422968-1"

[params]
    themeVariant = "blue"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
    name = "<i class='far fa-file fa-fw'></i> Curriculum Vitae"
    identifier = "cv"
    url = "/cv"
    weight = 20

[[menu.shortcuts]]
    name = "<i class='fas fa-exclamation-triangle fa-fw'></i> Disclaimer"
    identifier = "disclaimer"
    url = "/disclaimer"
    weight = 20

[[menu.shortcuts]] 
    name = "<i class='fab fa-github fa-fw'></i> GitHub Repo"
    identifier = "ds"
    url = "https://github.com/JianLoong"
    weight = 25

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = false
