baseURL = "https://jianliew.me/blog"
languageCode = "en-us"
title = "Jian Liew"
theme = "hugo-theme-learn"
publishDir = "docs"
googleAnalytics = "UA-55422968-1"
disqusShortname = "jianloonggithubio"

pygmentsUseClassic = true
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[markdown]
    extra = true

[taxonomies]
    tags = "tags"
    
[params]
    themeVariant = "blue"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
    name = "<i class='far fa-file fa-fw'></i>&nbsp;Curriculum Vitae"
    identifier = "cv"
    url = "/cv"
    weight = 20

[[menu.shortcuts]]
    name = "<i class='fas fa-history fa-fw'></i>&nbsp;Time Line"
    identifier = "timeline"
    url = "/timeline"
    weight = 25


[[menu.shortcuts]]
    name = "<i class='fas fa-tags fa-fw'></i>&nbsp;Tags"
    identifier = "Tags"
    url = "/tags"
    weight = 30


[[menu.shortcuts]]
    name = "<i class='fas fa-exclamation-triangle fa-fw'></i>&nbsp;Disclaimer"
    identifier = "disclaimer"
    url = "/disclaimer"
    weight = 35

[[menu.shortcuts]] 
    name = "<i class='fab fa-github fa-fw'></i>&nbsp;GitHub Repo"
    identifier = "ds"
    url = "https://github.com/JianLoong"
    weight = 40

[[menu.shortcuts]] 
    name = "<i class='fab fa-linkedin-in fa-fw'></i>&nbsp;Linkedin"
    identifier = "linkedin"
    url = "https://au.linkedin.com/in/jian-loong-liew-0433ab39"   
    weight = 45

[[menu.shortcuts]] 
    name = "<i class='fas fa-envelope-square fa-fw'></i>&nbsp;Email"
    identifier = "email"
    url = "mailto:jianloongliew@gmail.com"   
    weight = 50 

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = false
